# Generated by Django 4.1 on 2022-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_post_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.IntegerField(max_length=10),
        ),
    ]
